// Category configuration - Easy to add new categories!
const CATEGORY_CONFIG = {
    grade1: { label: "Grade 1", icon: "🌱" },
    grade2: { label: "Grade 2", icon: "🌿" },
    grade3: { label: "Grade 3", icon: "🌳" },
};

// Word data organized by category
const WORDS_BY_CATEGORY = {
    grade1: [
        { id: 67, french: "un", english: "one" },
        { id: 68, french: "une", english: "one" },
        { id: 69, french: "elle", english: "she" },
        { id: 70, french: "il y a", english: "there is" },
        { id: 71, french: "et", english: "and" },
        { id: 72, french: "j'ai", english: "I have" },
        { id: 73, french: "j'aime", english: "I like" },
        { id: 74, french: "les", english: "the" },
        { id: 75, french: "des", english: "some" },
        { id: 76, french: "avec", english: "with" },
        { id: 77, french: "c'est", english: "it is" },
        { id: 78, french: "est", english: "is" },
        { id: 79, french: "qui", english: "who" },
        { id: 80, french: "que", english: "that" },
        { id: 81, french: "oui", english: "yes" },
        { id: 82, french: "ici", english: "here" },
        { id: 83, french: "voici", english: "here is" },
        { id: 84, french: "chez", english: "at" },
        { id: 85, french: "aussi", english: "also" },
        { id: 86, french: "dans", english: "in" },
        { id: 87, french: "mange", english: "eat" },
        { id: 88, french: "je fais", english: "I do" },
        { id: 89, french: "je vois", english: "I see" },
        { id: 90, french: "je peux", english: "I can" },
        { id: 91, french: "je veux", english: "I want" },
        { id: 92, french: "je viens", english: "I come" },
        { id: 93, french: "je suis", english: "I am" },
        { id: 94, french: "est-ce que", english: "question word" },
        { id: 95, french: "parce-que", english: "because" },
        { id: 96, french: "beaucoup", english: "a lot" },
        { id: 97, french: "merci", english: "thank you" },
        { id: 98, french: "regarde", english: "look" },
    ],
    grade2: [
        { id: 35, french: "six", english: "six" },
        { id: 36, french: "dix", english: "ten" },
        { id: 37, french: "sept", english: "seven" },
        { id: 38, french: "huit", english: "eight" },
        { id: 39, french: "quatre", english: "four" },
        { id: 40, french: "cinq", english: "five" },
        { id: 41, french: "combien", english: "how many" },
        { id: 42, french: "dehors", english: "outside" },
        { id: 43, french: "aujourd'hui", english: "today" },
        { id: 44, french: "demain", english: "tomorrow" },
        { id: 45, french: "un homme", english: "a man" },
        { id: 46, french: "une femme", english: "a woman" },
        { id: 47, french: "le fils", english: "the son" },
        { id: 48, french: "la fille", english: "the daughter" },
        { id: 49, french: "une famille", english: "a family" },
        { id: 50, french: "quand", english: "when" },
        { id: 51, french: "pourquoi", english: "why" },
        { id: 52, french: "quelque chose", english: "something" },
        { id: 53, french: "il cherche", english: "he searches" },
        { id: 54, french: "j'ai faim", english: "I'm hungry" },
        { id: 55, french: "le soleil", english: "the sun" },
        { id: 56, french: "une feuille", english: "a leaf" },
        { id: 57, french: "maintenant", english: "now" },
        { id: 58, french: "l'heure", english: "the time" },
        { id: 59, french: "heureux", english: "happy" },
        { id: 60, french: "heureuse", english: "happy" },
        { id: 61, french: "les yeux", english: "the eyes" },
        { id: 62, french: "l'œil", english: "the eye" },
        { id: 63, french: "derrière", english: "behind" },
        { id: 64, french: "le coin", english: "the corner" },
        { id: 65, french: "jusqu'à", english: "until" },
        { id: 66, french: "presque", english: "almost" },
    ],
    grade3: [
        { id: 1, french: "à propos", english: "about" },
        { id: 2, french: "à travers", english: "through" },
        { id: 3, french: "au dessus", english: "above" },
        { id: 4, french: "au dessous", english: "below" },
        { id: 5, french: "aussitôt", english: "immediately" },
        { id: 6, french: "automne", english: "autumn" },
        { id: 7, french: "besoin", english: "need" },
        { id: 8, french: "bientôt", english: "soon" },
        { id: 9, french: "chacun", english: "each" },
        { id: 10, french: "combien", english: "how many" },
        { id: 11, french: "comment", english: "how" },
        { id: 12, french: "devant", english: "in front" },
        { id: 13, french: "en arrière", english: "behind" },
        { id: 14, french: "ensuite", english: "then" },
        { id: 15, french: "jamais", english: "never" },
        { id: 16, french: "long", english: "long" },
        { id: 17, french: "longtemps", english: "a long time" },
        { id: 18, french: "lorsque", english: "when" },
        { id: 19, french: "monsieur", english: "mister" },
        { id: 20, french: "parfois", english: "sometimes" },
        { id: 21, french: "partout", english: "everywhere" },
        { id: 22, french: "pendant", english: "during" },
        { id: 23, french: "personne", english: "nobody" },
        { id: 24, french: "peut-être", english: "maybe" },
        { id: 25, french: "plusieurs", english: "several" },
        { id: 26, french: "seulement", english: "only" },
        { id: 27, french: "souvent", english: "often" },
        { id: 28, french: "temps", english: "time" },
        { id: 29, french: "vraiment", english: "really" },
        { id: 30, french: "elles montrent", english: "they show" },
        { id: 31, french: "ils choisissent", english: "they choose" },
        { id: 32, french: "nous sommes", english: "we are" },
        { id: 33, french: "elles prennent", english: "they take" },
        { id: 34, french: "ils étaient", english: "they were" },
    ]
};

// Settings
const SETTINGS = {
    multipleChoiceCount: 2,
    quizDirection: 'french-to-english',
};